# Generated by Django 5.1.1 on 2025-11-25 11:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('poll_url', models.URLField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(default='paynow', max_length=50)),
                ('whatsapp_number', models.CharField(db_index=True, help_text="User's WhatsApp number", max_length=15)),
                ('payment_number', models.CharField(db_index=True, help_text='Mobile payment number', max_length=15)),
                ('reference', models.CharField(blank=True, help_text='Internal reference', max_length=255)),
                ('paynow_reference', models.CharField(blank=True, help_text='PayNow reference', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['whatsapp_number', 'status'], name='payment_pay_whatsap_155562_idx'), models.Index(fields=['payment_number', 'status'], name='payment_pay_payment_fd8c57_idx')],
            },
        ),
    ]
