# Generated by Django 5.1.1 on 2025-11-25 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='core_accomm_phone_n_b1cd53_idx'), models.Index(fields=['verified'], name='core_accomm_verifie_f8b3c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_number', models.CharField(db_index=True, max_length=20)),
                ('agent_id', models.CharField(db_index=True, max_length=100)),
                ('time_of_active_of_the_agent', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['cell_number', 'agent_id'], name='core_conver_cell_nu_193830_idx'), models.Index(fields=['time_of_active_of_the_agent'], name='core_conver_time_of_eec4be_idx'), models.Index(fields=['is_suspicious'], name='core_conver_is_susp_a0ea34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_number', models.CharField(db_index=True, max_length=20)),
                ('current_step', models.CharField(choices=[('inquiry', 'Inquiry'), ('token_check', 'Token Check'), ('payment', 'Payment'), ('property_selection', 'Property Selection'), ('booking_confirmation', 'Booking Confirmation'), ('additional_info', 'Additional Info'), ('completed', 'Completed')], default='inquiry', max_length=50)),
                ('context_data', models.JSONField(default=dict)),
                ('selected_properties', models.JSONField(default=list)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['cell_number', 'is_active'], name='core_conver_cell_nu_dfc274_idx'), models.Index(fields=['current_step'], name='core_conver_current_2456cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_no', models.CharField(db_index=True, help_text='Property reference number (2 letters followed by a hyphen and 4 digits, e.g. AB-1234)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Property number must be 2 capital letters followed by a hyphen and 4 digits (e.g. AB-1234)', regex='^[A-Z]{2}-[0-9]{4}$')])),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('total_rooms', models.PositiveIntegerField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('available_1h_rooms', models.PositiveIntegerField(default=0)),
                ('available_2h_rooms', models.PositiveIntegerField(default=0)),
                ('available_3h_rooms', models.PositiveIntegerField(default=0)),
                ('available_4h_rooms', models.PositiveIntegerField(default=0)),
                ('amenities', models.JSONField(default=list)),
                ('price_per_semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('distance_from_campus', models.FloatField(help_text='Distance in kilometers')),
                ('campus_name', models.CharField(max_length=100)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any'), ('mixed', 'Mixed')], default='any', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.accommodationprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_number', models.CharField(db_index=True, default='', max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rental_period', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], default='month', max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provider_response', models.TextField(blank=True)),
                ('additional_info_requested', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_number', models.CharField(db_index=True, max_length=20)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_number', models.CharField(db_index=True, max_length=20)),
                ('transaction_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('ecocash', 'EcoCash'), ('paynow', 'Paynow')], max_length=20)),
                ('pop_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('pop_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed ', 'failed ')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_number'], name='core_transa_transac_b96e2d_idx'), models.Index(fields=['cell_number'], name='core_transa_cell_nu_d2c72a_idx'), models.Index(fields=['status'], name='core_transa_status_288ab7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_number', models.CharField(db_index=True, max_length=20)),
                ('token_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='core.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'available_rooms'], name='core_proper_is_acti_457663_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['campus_name'], name='core_proper_campus__649eec_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['gender_preference'], name='core_proper_gender__44a973_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_per_month'], name='core_proper_price_p_adad14_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['distance_from_campus'], name='core_proper_distanc_e1a913_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'campus_name', 'available_rooms'], name='core_proper_is_acti_ea8bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='core_bookin_booking_2e4e10_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['cell_number'], name='core_bookin_cell_nu_1ad8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='core_bookin_status_fe12a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('cell_number', 'property', 'status')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['property', 'rating'], name='core_review_propert_24ea91_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['cell_number'], name='core_review_cell_nu_fd4c9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('cell_number', 'property')},
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token_number'], name='core_token_token_n_d5584c_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['cell_number'], name='core_token_cell_nu_629c91_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['is_active', 'expires_at'], name='core_token_is_acti_616e10_idx'),
        ),
    ]
