# Generated by Django 5.1.1 on 2025-12-01 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-rating', 'price_per_month', 'distance_from_campus']},
        ),
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rating'], name='core_proper_rating_992879_idx'),
        ),
    ]
